name: my_ticket
services:
  app:
    container_name: my_ticket_app
    build: ../../../
    ports:
      - '8081:8081'
    depends_on:
      - postgres
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/my_ticket'
      - 'SPRING_DATASOURCE_USERNAME=my_ticket'
      - 'SPRING_DATASOURCE_PASSWORD=my_ticket'

  postgres:
    container_name: my_ticket_db
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=my_ticket'
      - 'POSTGRES_PASSWORD=my_ticket'
      - 'POSTGRES_USER=my_ticket'
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local